spring.application.name=Manufacturing-Enterprise-MRP-Engine

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/infotact_mrp?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Script Initialization Order Adjustments
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always