package com.mrp_engine.controller;

import com.mrp_engine.model.PurchaseOrder;
import com.mrp_engine.repository.PurchaseOrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/purchase-orders")
@CrossOrigin(origins = "http://localhost:5173")
public class PurchaseOrderController {

    @Autowired
    private PurchaseOrderRepository poRepository;

    // View all orders generated by the engine
    @GetMapping
    public List<PurchaseOrder> getAllOrders() {
        return poRepository.findAll();
    }

    // Approve an order to mock inventory fulfillment
    @PutMapping("/{id}/approve")
    public ResponseEntity<?> approveOrder(@PathVariable Long id) {
        return poRepository.findById(id).map(po -> {
            po.setStatus("APPROVED");
            poRepository.save(po);
            return ResponseEntity.ok(Map.of("message", "Order approved successfully!"));
        }).orElse(ResponseEntity.notFound().build());
    }
}